### ISSUE TITLE
Get package on MELPA

### ISSUE THREAD

**Issue by josteink** [jschaf/powershell.el#11]
MELPA has in the past allowed superseding forks to replace the original packages.

Dino Chiesa has formerly also abandoned other projects, like (now mine) [csharp-mode](https://github.com/josteink/csharp-mode), and getting both MELPA and MARMALADE to accept the new packages was relatively little work.

So for "the greater good" of Emacs-users and seamless installation and deployment, this really should be done sooner rather than later.

**Comment by jschaf** [comment]
Good point, this should be a pretty easy sell given the explicit permission from Dino.

**Comment by jschaf** [comment]
I forgot that I already put it on melpa.  http://melpa.org/#/powershell

Here's the pull request that did it https://github.com/milkypostman/melpa/pull/1923
