### ISSUE TITLE
PowerShell 5.0, Class / Enum support

### ISSUE THREAD

**Issue by adamedx** [jschaf/powershell.el#6]
PowerShell 5.0 supports [new features](https://technet.microsoft.com/en-us/library/hh857339.aspx#BKMK_newcore) including classes and enums -- it would be great to get the syntax highlighting for these new features.

**Comment by jschaf** [comment]
Okay, I'll take a look.  That should be a pretty quick fix.

**Comment by jschaf** [comment]
Lemme know if this update works for you.

**Comment by adamedx** [comment]
It does work indeed @jschaf -- this is excellent! Thank you, let's hope they don't add more syntax changes before PowerShell 5 goes GA.

Thank you for maintaining this.
